FROM alpine:3

ARG TARGETARCH

WORKDIR /app
RUN apk upgrade && apk --no-cache add ca-certificates tzdata curl gcompat
RUN mkdir -p /app/data

COPY ./backend/.bin/arcane-agent-linux-${TARGETARCH} ./arcane-agent

ENV ENVIRONMENT=production \
    AGENT_MODE=true \
    GIN_MODE=release \
    PORT=3553

LABEL org.opencontainers.image.title="Arcane Agent"
LABEL org.opencontainers.image.description="Arcane Agent"
LABEL org.opencontainers.image.source="https://github.com/ofkm/arcane"
LABEL com.ofkm.arcane.updater="false"
LABEL com.ofkm.arcane.server="true"

EXPOSE 3553
VOLUME ["/app/data"]

CMD ["./arcane-agent"]