FROM alpine:3

ARG TARGETARCH

WORKDIR /app
RUN apk upgrade && apk --no-cache add ca-certificates tzdata curl
RUN mkdir -p /app/data

COPY ./backend/.bin/arcane-linux-${TARGETARCH} ./arcane

ENV ENVIRONMENT=production
ENV GIN_MODE=release
ENV PORT=3552

LABEL org.opencontainers.image.title="Arcane"
LABEL org.opencontainers.image.description="Modern Docker Management, Made for Everyone"
LABEL org.opencontainers.image.source="https://github.com/ofkm/arcane"
LABEL com.ofkm.arcane.updater="false"
LABEL com.ofkm.arcane.server="true"

EXPOSE 3552
VOLUME ["/app/data"]

CMD ["./arcane"]