import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Sidebar configuration for Arcane documentation
 */
const sidebars: SidebarsConfig = {
  docs: [
    // Introduction (homepage)
    "intro",
    // Getting Started section
    {
      type: "category",
      label: "Getting Started",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "getting-started",
        },
      ],
    },

    // Features section with nested categories
    {
      type: "category",
      label: "Features",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "features",
        },
      ],
    },

    // How-to Guides
    {
      type: "category",
      label: "Guides",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "guides",
        },
      ],
    },

    // Development/Contributing
    {
      type: "category",
      label: "Development",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "development",
        },
      ],
    },
  ],
};

export default sidebars;
